export const CART_DISPATCH='CART_DISPATCH';
export const CART_COUNT_DISPATCH='CART_COUNT_DISPATCH';

export const LOGIN_DISPATCH='LOGIN_DISPATCH';
export const LOG_DISPATCH='LOG_DISPATCH';


export const LOAD_DATA_DISPATC=' LOAD_DATA_DISPATC';